PR - 29 - [Login] Implementar service de token
FGA0138-MDS-Ajax/2024.2-Wunjo pull request #51
Opened 2024-12-24 01:19 UTC by gabemagioli

- Implementação do jwt token manager

2024-12-24 01:41 UTC, sluucke commented on backend/src/infra/services/shared/token/jwt-token-manager.ts
> +          const studentId = data.id;//getting the student id and passing on the token
Realmente precisa desse comentario?

2024-12-24 01:45 UTC, sluucke requested changes

2024-12-24 01:45 UTC, sluucke commented on backend/src/infra/services/shared/token/jwt-token-manager.ts
> +    SECRET_KEY: string = "unbordoJWTsecretkey*4#$@);.";
Nessa `SECRET_KEY` dá para colocar um valor no ENV assim poderemos mudar a secret key facilmente dependendo da plataforma que estamos rodando ficando até mesmo mais anônimo, o código do GitHub é publico, com essa chave damos a liberdade de qualquer usuário criar um token em nossa plataforma ou descriptografar um token de usuário da nossa plataforma, caracterizando uma falha de segurança.

```suggestion
    SECRET_KEY: string = env.JWT_SECRET_KEY
```

Após aplicar a sugestão será necessário adicionar no arquivo local de variável ambiente `.env.local` ou `.env.dev` e `.env.example`, além disso, alterar o arquivo `env.ts` localizado em `src/env.ts`

2024-12-24 01:45 UTC, sluucke commented on backend/src/infra/services/shared/token/jwt-token-manager.ts
> +                expiresIn: '7 days',
Aqui também dá pra alterar para puxar de uma variável de ambiente, assim conseguiremos regular o tempo de expiração em desenvolvimento e produção.
```suggestion
                expiresIn: env.JWT_TOKEN_EXPIRES_IN,
```

2024-12-24 01:50 UTC, gabemagioli commented on backend/src/infra/services/shared/token/jwt-token-manager.ts
> +          const studentId = data.id;//getting the student id and passing on the token
coloquei pq como o tipo data ta como object achei q fosse mlhr especificar que era do estudante

2024-12-24 02:46 UTC, sluucke commented on backend/src/infra/services/token/jwt-token-manager.ts
> +import { StudentTokenManager, StudentTokenManagerGenerateInput } from '@/application/services/token/token-manager-service';
```suggestion
import { StudentTokenManager, StudentTokenManagerGenerateInput } from '@/application/services';
```

2024-12-26 14:09 UTC, sluucke commented on backend/tests/unit/services/shared/zod/auth/jwt-token-manager-zod-service.test.ts
> +    expect(output).toBeInstanceOf(Object);
Acredito que aqui dê pra você melhorar um pouco a espera desse caso de teste, além de verificar a instância que tal verificar também se a saida de `output` está correta?

2024-12-27 01:02 UTC, gabemagioli commented on backend/tests/unit/services/shared/zod/auth/jwt-token-manager-zod-service.test.ts
> +    expect(output).toBeInstanceOf(Object);
mas como o token vai ser diferente toda vez que rodar, como posso testar o output?

2024-12-27 14:46 UTC, sluucke commented on backend/tests/unit/services/shared/zod/auth/jwt-token-manager-zod-service.test.ts
> +    expect(output).toBeInstanceOf(Object);
o decrypt é justamente pra descriptografar os dados, ou seja, você envia um token e recebe os dados esse output não é token e sim os dados, dá um console log nesse input q vc vai ver

2024-12-27 16:18 UTC, sluucke approved these changes

2024-12-27 16:21 UTC, Sophiassilva submitted a review, later dismissed

2024-12-29 03:29 UTC, sluucke submitted a review, later dismissed

2024-12-29 11:23 UTC, Sophiassilva submitted a review, later dismissed

2024-12-29 19:39 UTC, sluucke approved these changes

2024-12-29 21:44 UTC, merged